### ISSUE TITLE
Signing transaction

### ISSUE THREAD

**Issue by vlsilver** [reaster/cardano_wallet_sdk#1]
This library does not support signing transactions yet ?
I have read the implementation of the sendAda  method:

  @override
  Future<Result<RawTransaction, String>> sendAda(
      {required ShelleyAddress toAddress, required int lovelaceAmount}) async {
    if (lovelaceAmount > balance) {
      return Err('insufficient balance');
    }
    if (toAddress.addressType != AddressType.Base) {
      return Err('only base shelley addresses currently supported');
    }
    if (toAddress.hrp != 'addr' && toAddress.hrp != 'addr_test') {
      return Err("not a valid shelley external addresses, expecting 'addr' or 'addr_test' prefix");
    }
    final builder = TransactionBuilder().send(shelleyAddress: toAddress, lovelace: lovelaceAmount);
    //TODO calculate, fee, make change, sign and send
    return Err('not yet implmented');
  }

**Comment by reaster** [comment]
Transaction submits now work!
