### ISSUE TITLE
Cached wallets not persisted after app relaunch

### ISSUE THREAD

**Issue by mtkgeek** [reaster/cardano_wallet_sdk#2]
Hi, how long are the cached wallets supposed to persist? I was thinking until they're cleared or if I uninstall the app but that's not the case. I lose all my cached wallets with every app restart.

**Comment by reaster** [comment]
For the Fund 5 prototype, there was no plans to have a persistent cache, but the interface provides a path for future work.

**Comment by mtkgeek** [comment]
Ok, thanks for pointing that out. Is there any other way I can retrieve wallets on app launch, maybe using just the ids or something?

**Comment by reaster** [comment]
Not without local persistence. For now you'll have to use something like [encrypted_shared_preferences](https://pub.dev/packages/encrypted_shared_preferences) to store the private key and rebuild the wallet from blockfrost calls.

**Comment by mtkgeek** [comment]
I would really appreciate a code sample on how to do this. Not the encrypted shared preferences part, just how to rebuild a wallet from a blockfrost call using a private key.

**Comment by reaster** [comment]
You pass the private key (rootSigningKey) to the WalletBuilder, call build() and then get updates using wallet.update():  
```
  final walletBuilder = WalletBuilder()
    ..networkId = NetworkId.testnet
    ..testnetAdapterKey = blockfrostKey
    ..rootSigningKey = rootSigningKey;
  Result<Wallet, String> result = walletBuilder.build();
  Wallet wallet = result.unwrap();
  for (int i = 0; i < 20; i++) {
    sleep(Duration(seconds: 1));
    var result2 = await wallet.update();
    result2.when(
      ok: (changed) => print("#$i: ${wallet.balance} Lovelace, changed: $changed"),
      err: (message) => print("Error: $message"),
    );
  }
```
You can use this snippet to get a private key from a mnemonic (and Bech32 encoding to get stringy):
```
  final mnemonic = 'army bid park alter ...';
  final hdWallet = HdWallet.fromMnemonic(mnemonic);
  final Bip32SigningKey rootSigningKey = hdWallet.rootSigningKey;
```
Until I get around to making a local private key class, you'll need to import bip32_ed25519. 
```
import 'package:bip32_ed25519/bip32_ed25519.dart';  
```

**Comment by mtkgeek** [comment]
Thank you for this. Although this should work for transactional wallets, it won't work for a read only wallet though because according to the docs they don't have signing keys. How would you suggest i rebuild a read only wallet, should I encrypt the user's mnemonic phrase and use that instead? I don't think that's a great idea though.

**Comment by reaster** [comment]
The private/signing key is generated from the mnemonic, so by definition that would be a transactional wallet. I'd store the private key for transactional wallets and the staking address for read-only wallets as Bech32 strings. You can use the Bech32 prefix (see https://cips.cardano.org/cips/cip5/) to determine which key you have, namely read-only wallet keys will always start with 'stake', then encode it to the correct type and pass it to the builder.
